# Generated by Django 4.1.7 on 2023-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
