# Generated by Django 4.1.7 on 2023-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='employee',
            name='working_task',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
