# Generated by Django 4.1.7 on 2023-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0002_delete_size_employee_working_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_task',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
