# Generated by Django 4.1.7 on 2023-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0003_alter_employee_working_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
