# Generated by Django 4.1.7 on 2023-06-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0003_employee_salary_employee_total_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='task',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
