# Generated by Django 4.1.7 on 2023-06-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0008_size_task_alter_employee_clock_out_time_employeetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task',
        ),
    ]
