# Generated by Django 4.1.7 on 2023-06-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0010_remove_employeetask_size_employeetask_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='sizes',
        ),
    ]
