# Generated by Django 4.1.7 on 2023-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out', '0011_remove_employeetask_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
